<?php
// $ID$

module_load_include('php', 'wisski_salz', "adapters/csv/CSVAdapter");
module_load_include('php', 'wisski_salz', "interface/AdapterInterface");

/**
* implements hook_menu()
*/
function csv_adapter_menu(){
    $items = array();
    $store_type = csv_adapter_wisski_get_store_type();
//    $key = _csv_adapter_get_db_key();

    $result = db_select('wisski_salz_store_types', 'types')
    ->fields('types', array('name'))
    ->condition('label', csv_adapter_wisski_get_store_type(), 'LIKE')
    ->execute()->fetchObject();
    if(!empty($result)) $store_type_name = $result->name;

    //$items['admin/config/wisski/salz/add/' . $key] = array(
    $items['admin/config/wisski/salz/add/' . $store_type_name] = array(
      'title' => 'Add new store of type ' . $store_type,
      'description' => 'Manage the storage backends',
      'type' => MENU_NORMAL_ITEM,
//      'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('csv_adapter_add_form'),
      'access arguments' => array('administer wisski'),
    ); 

    $store_instances = csv_adapter_wisski_get_store_instances();
    foreach($store_instances as $key => $store_instance) {
	    $items['admin/config/wisski/salz/edit/' . $store_type_name . '/' . $store_instance->name] = array(
		    'title' => 'Edit ' . $store_type . ' Store ' . $store_instance->label,
		    'description' => 'Manage the storage backends',
		    'type' => MENU_LOCAL_TASK,
		    //'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('csv_adapter_edit_form'),
		    'access arguments' => array('administer wisski'),
            );   
	    $items['admin/config/wisski/salz/delete/' . $store_type_name . '/' . $store_instance->name] = array(
		    'title' => 'Delete Store ' . $store_type . ' ' . $store_instance->label,
		    'description' => 'Manage the storage backends',
		    'type' => MENU_NORMAL_ITEM,
		    //'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
		    'page callback' => 'drupal_get_form',
		    'page arguments' => array('csv_adapter_delete_form'),
		    'access arguments' => array('administer wisski'),
            );   
    } 

    return $items; 
}


function csv_adapter_wisski_get_store_settings(){
    $adapter = new CSVAdapter();
    return $adapter->getSettings();
}

function csv_adapter_wisski_get_store(){
    $adapter = new CSVAdapter();
    return $adapter;
}

function csv_adapter_wisski_get_store_type(){
    return "CSV";
}

function csv_adapter_wisski_get_store_instances(){
	return db_select('wisski_salz_csv_store_instances', 'ins')
		->fields('ins')
		->condition('deleted', 0, '=')
		->condition('type', _csv_adapter_get_db_key(), '=')
		->execute()->fetchAllAssoc('name');
	    
}

    $csv_adapter_db_key = -1;

function _csv_adapter_get_db_key(){
	global $csv_adapter_db_key;
	if ($csv_adapter_db_key == -1 || $csv_adapter_db_key == NULL){
		$result = db_select('wisski_salz_store_types', 'types')
			->fields('types', array('stid'))
			->condition('label', csv_adapter_wisski_get_store_type(), 'LIKE')
			->execute()->fetchObject();
		if(!empty($result)) $csv_adapter_db_key = $result->stid;
	}
	return $csv_adapter_db_key;
}

function csv_adapter_db_insert_settings($settings, $clean = TRUE){
	if ($clean) {
		$settings['type'] = _csv_adapter_get_db_key();
		db_insert('wisski_salz_csv_store_instances')
			->fields($settings)->execute();
	} else {
		$old_name = $settings['old_name'];
		unset($settings['old_name']);
		db_update('wisski_salz_csv_store_instances')
			->fields($settings)->condition('name', $old_name, 'LIKE')->execute();
	}
}

function csv_adapter_settings_page($store_instance_name = "", $clean){
    if (!$clean){
	    try{
		    $instance = csv_adapter_wisski_db_get_instance_by_name($store_instance_name);
	    } catch(Exception $ex){
		    drupal_set_message("There was an error loading store_instance $store_instance_name<br>Error Message: " . $ex->getMessage());
		    $clean = TRUE;
	    }
}
    $form['name'] = array(
        '#type' => 'textfield',
	'#title' => t('Name'),
	'#default_value' => ($clean ? '' : $instance->label),
        '#description' => t('The human-readable name of the store.'),	
    );
    
     $form['file_path'] = array(
        '#type' => 'textfield',
	'#title' => t('File Path'),
	'#default_value' => ($clean ? '' : $instance->file_path),
        '#description' => t('The path to the CSV File.'),	
    );    

    
     $form['separators'] = array(
        '#type' => 'textfield',
	'#title' => t('Separators'),
	'#default_value' => ($clean ? '' : $instance->separators),
        '#description' => t('A group of characters that are separating the entries of the file.'),	
    );
    
    
     $form['allowed_chars'] = array(
        '#type' => 'textfield',
	'#title' => t('Allowed Chars'),
	'#default_value' => ($clean ? '' : $instance->allowed_chars),
        '#description' => t('A group of allowed characters.'),	
    );

    
    $form['delimiters'] = array(
        '#type' => 'textfield',
	'#title' => t('Delimiters'),
	'#default_value' => ($clean ? '' : $instance->delimiters),
        '#description' => t('Pairs of surrounding delimiters of strings.'),	
    );
    
    $form['headline'] = array(
        '#type' => 'checkbox',
	'#title' => t('The file contains a headline'),
	'#default_value' => ($clean ? '' : $instance->headline),
       // '#description' => t('Checked if the file contains a headline.'),	
    );
    
    $form['auto_inc_key'] = array(
        '#type' => 'textfield',
	'#title' => t('Auto incrementation key'),
	'#default_value' => ($clean ? '' : $instance->auto_inc_key),
        '#description' => t('The column number of the key value used for auto-incrementation.'),	
    );
    
    $form['name_key'] = array(
        '#type' => 'textfield',
	'#title' => t('Name Key'),
	'#default_value' => ($clean ? '' : $instance->name_key),
        '#description' => t('The name or column number of the (human-readable) unique key that identifies the row.'),	
    );
    $form['submit'] = array(
	    '#type' => 'submit',
	    '#value' => t('Save'),
	    '#submit' => array('csv_adapter_form_submit'),
	    '#weight' => 20,
    );

	if(!$clean){
            $form['actions']['delete'] = array(
                '#type' => 'submit',
		'#value' => t('Delete this store'),
		'#submit' => array('csv_adapter_submit_delete_form'),
		'#weight' => 22,
	   );
	}
return $form;
}

function csv_adapter_form_submit($form, &$form_state, $store_instance = NULL){
    if(arg(4)=="add"){
        $label = $form_state['values']['name'];
        $name = preg_replace('/[^a-z0-9_]/u' , '', strtolower($label));
        $settings = array(
	    'name' => $name,
	    'label' => $label,
	    'file_path' => $form_state['values']['file_path'],
	    'separators' => $form_state['values']['separators'],
	    'allowed_chars' => $form_state['values']['allowed_chars'],
	    'delimiters' => $form_state['values']['delimiters'],
	    'headline' => $form_state['values']['headline'],
	    'auto_inc_key' => $form_state['values']['auto_inc_key'],
	    'name_key' => $form_state['values']['name_key'],
        );
        csv_adapter_db_insert_settings($settings);
        drupal_set_message("Saved settings.");
        $installed_store_instances = csv_adapter_wisski_get_store_instances();
        foreach($installed_store_instances as $key => $installed_store_instance){
            $form_state['redirect'] = 'admin/config/wisski/salz/edit/'. arg(5) . '/' . $installed_store_instance->name;
        }
        menu_rebuild();
    } else {
	    drupal_set_message("Changed settings.");
	    $form_state['redirect'] = 'admin/config/wisski/salz/';
	    $label = $form_state['values']['name'];
	    $name = preg_replace('/[^a-z0-9_]/u', '', strtolower($label));
	    $settings = array(
		    'old_name' => arg(6),
		    'name' => $name,
		    'label' => $label,
		    'file_path' => $form_state['values']['file_path'],
		    'separators' => $form_state['values']['separators'],
		    'allowed_chars' => $form_state['values']['allowed_chars'],
		    'delimiters' => $form_state['values']['delimiters'],
		    'headline' => $form_state['values']['headline'],
		    'auto_inc_key' => $form_state['values']['auto_inc_key'],
		    'name_key' => $form_state['values']['name_key'],
	    );
	    csv_adapter_db_insert_settings($settings, FALSE);
    }
    menu_rebuild();
}

function csv_adapter_wisski_db_get_instance_by_name($name){
	return db_select('wisski_salz_csv_store_instances', 'ins')
		->fields('ins')
		->condition('name', $name, 'LIKE')
		->execute()->fetchObject();
}

function csv_adapter_delete_store_instances($instance_to_delete = NULL){
	if ($instance_to_delete == NULL) $instance_to_delete = arg(6);
	$result = db_select('wisski_salz_csv_store_instances', 'ins')
		->fields('ins')
		->condition('deleted', 0, '=')
		->condition('name', $instance_to_delete, 'LIKE')
		->execute();
	if (empty($result)) drupal_set_message("Instance $instance_to_delete does not exist or has already been deleted");
	else {
		db_update('wisski_salz_csv_store_instances')
			->fields(array('deleted' => 1))
			->condition('name', $instance_to_delete, 'LIKE')
			->execute();
		return TRUE;
	}
	return FALSE;
}

function csv_adapter_add_form($form, &$form_state){
    return csv_adapter_settings_page(arg(6), TRUE);
}

function csv_adapter_edit_form($form, &$form_state){
    return csv_adapter_settings_page(arg(6), FALSE);
}

function csv_adapter_submit_delete_form($form, &$form_state){
    // Redirect user to "delete" uri for this store.
    $form_state['redirect'] = 'admin/config/wisski/salz/delete/' . arg(5) . '/' . arg(6);
}

function csv_adapter_delete_form($form, &$form_state){
    $message = t('Are you sure you want to delete store CSV ' . arg(6) . '?');
    $path = 'admin/config/wisski/salz/edit' . arg(5) . '/' . arg(6);
    return confirm_form(
	    $form,
	    $message,
	    $path,
	    t('Only do this if you are sure!'),
	    t('Delete'),
	    t('Cancel')
    );
}


function csv_adapter_delete_form_submit($form, &$form_state){
	$result = csv_adapter_delete_store_instances();
	menu_rebuild();
	if ($result) {
		drupal_set_message("The store CSV " . arg(6) . " was successfully deleted.");
	}
	$form_state['redirect'] = 'admin/config/wisski/salz';
}

/*function csv_adapter_test() {
    
  $adapter = new CSVAdapter('file','sites/all/modules/wisski/wisski_salz/adapters/csv/testfile.txt');
  
}*/

