<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\wisski_triplify\TriplifyManager;

function wisski_triplify_wisski_individual_view(array &$build, EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
#dpm("begin triplify", "aa");
#  $success = (new TriplifyManager())->triplify($entity);
#dpm($success);
#  $success = (new TriplifyManager())->triplify($entity);
  
}


function wisski_triplify_wisski_individual_update(EntityInterface $entity) {
  $success = (new TriplifyManager())->triplify($entity);
}

function wisski_triplify_wisski_individual_insert(EntityInterface $entity) {
  $success = (new TriplifyManager())->triplify($entity);
}


