<?php

use Drupal\wisski_core\WisskiEntityInterface;
use Drupal\wisski_core\Entity\WisskiEntity;

use Drupal\wisski_core\WisskiCacheHelper;

function wisski_core_cache_flush() {

  WisskiCacheHelper::flushAllEntityTitles();
  WisskiCacheHelper::flushAllPreviewImageUris();
  drupal_set_message(t('Flushed WissKI specific caches'));
}

function wisski_core_generate_title($wisski_individual,$force_new=FALSE) {

//  ddebug_backtrace();
  
  $create_form_title = FALSE;
  if ($wisski_individual instanceof WisskiEntityInterface) {
    if ($wisski_individual->isNew()) $create_form_title = TRUE;
    $entity_id = $wisski_individual->id();
    $bundle_id = $wisski_individual->bundle();
  } else {
    $entity_id = $wisski_individual;
    $bundle_id = WisskiCacheHelper::getCallingBundle($wisski_individual);
  }
  $title = '';
  if (!empty($bundle_id)) {
    if ($bundle = \Drupal\wisski_core\Entity\WisskiBundle::load($bundle_id)) {
      if ($create_form_title) $title = html_entity_decode(t('New :bundle_label',array(':bundle_label'=>$bundle->label()))->render());
      else $title = $bundle->generateEntityTitle($entity_id,FALSE,$force_new);
    }
  }
  if (empty($title)) {
    $title = \Drupal::service('entity_type.manager')->getDefinition('wisski_individual')->getLabel().' '.$entity_id;
    drupal_set_message(t('No title could be generated for this entity'),'warning');
  }
  return $title;
  
}

function wisski_core_flush_title_caches($bundle_ids=NULL,$entity_ids=NULL) {

  if (is_null($bundle_ids)) {
    \Drupal\wisski_core\WisskiCacheHelper::flushAllEntityTitles();
    return;
  }
  $bundles = \Drupal\wisski_core\Entity\WisskiBundle::loadMultiple($bundle_ids);
  foreach ($bundles as $bundle) {
    $bundle->flushTitleCache($entity_ids);
  }
}

function wisski_trace($dpm=TRUE) {

  $trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS,3);
  if ($dpm && function_exists('dpm')) {
    $label = (string) $trace[1]['function'].'() called from';
    dpm(array($label => $trace[2]),__METHOD__);
  }
  return $trace[2];
}

function wisski_tick($name='') {
  
  static $wisski_timestamp;
  $now = microtime(TRUE)*1000;
  if (empty($name)) {
    if (!isset($wisski_timestamp)) $wisski_timestamp = $now;
  } else {
    $diff = ceil($now-$wisski_timestamp);
    if (!empty($name)) {
      dpm($diff.' ms',$name);
      \Drupal::logger('wisski tick')->debug($name);
    } else {
      \Drupal::logger('wisski tick')->debug("reset");
    }
    $wisski_timestamp = $now;
    return $diff;
  }
}


function wisski_local_store_query($query,$select=NULL) {
  
  $adapter = \Drupal\wisski_salz\AdapterHelper::getPreferredLocalStore();
  $out = array();
  foreach ($adapter->getEngine()->directQuery($query) as $obj) {
    if (isset($select)) {
      $sub = array();
      foreach ($select as $prop) {
        if (property_exists($obj,$prop)) {
          $val = $obj->{$prop};
          if (method_exists($val,'getUri'))
            $sub[$prop] = $val->getUri();
          else
            $sub[$prop] = $val->dumpValue('text');
        }
      }
      if (!empty($sub)) $out[] = $sub;
    } else {
      $sub = array();
      foreach ((array) $obj as $prop => $val) {
        if (method_exists($val,'getUri'))
          $sub[$prop] = $val->getUri();
        else
          $sub[$prop] = $val->dumpValue('text');
      }
      if (!empty($sub)) $out[] = $sub;
    }
  }
  return $out;
}
