<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use \Drupal\wisski_pathbuilder\Entity\WisskiPathbuilderEntity;
use \Drupal\wisski_pathbuilder\Entity\WisskiPathEntity;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Render\Element\RenderElement;
use Drupal\Core\Render\Element;


/**
 * Menu arugment loader. Returns a pathbuilder entity
 *
 * @param $id
 * @return \Drupal\Core\Entity\EntityInterface|static
 */

function wisski_pathbuilder_load($id) {
  return WisskiPathbuilderEntity::load($id);
}

function wisski_pathbuilder_path_load($id) {
  return WisskiPathEntity::load($id);
}

function wisski_pathbuilder_help($route_name, RouteMatchInterface $route_match) {
   switch ($route_name) {
    case 'help.page.wisski_pathbuilder':
      return '<p>' . t('This is the basic WissKI module for building ' .
        'pathbuilders, paths and groups. You will need that if you want to do ' .
        'anything with WissKI.') . '</p>';
  }
}

/* The following hook implementations don't seem to work ... */

/** Implementation of hook_ENTITY_TYPE_insert for pathbuilder entity type
 */
function wisski_pathbuilder_wisski_pathbuilder_insert (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}

/** Implementation of hook_ENTITY_TYPE_update for pathbuilder entity type
 */
function wisski_pathbuilder_wisski_pathbuilder_update (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}

/** Implementation of hook_ENTITY_TYPE_delete for pathbuilder entity type
 */
function wisski_pathbuilder_wisski_pathbuilder_delete (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}

/** Implementation of hook_ENTITY_TYPE_insert for path entity type
 */
function wisski_pathbuilder_wisski_path_insert (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}

/** Implementation of hook_ENTITY_TYPE_update for path entity type
 */
function wisski_pathbuilder_wisski_path_update (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}

/** Implementation of hook_ENTITY_TYPE_delete for path entity type
 */
function wisski_pathbuilder_wisski_path_delete (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}

/** Implementation of hook_ENTITY_TYPE_insert for adapter entity type
 */
function wisski_pathbuilder_wisski_salz_adapter_insert (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}

/** Implementation of hook_ENTITY_TYPE_update for adapter entity type
 */
function wisski_pathbuilder_wisski_salz_adapter_update (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}

/** Implementation of hook_ENTITY_TYPE_delete for adapter entity type
 */
function wisski_pathbuilder_wisski_salz_adapter_delete (EntityInterface $entity) {
  \Drupal::service('wisski_pathbuilder.manager')->reset();
}


// Used the code of https://www.drupal.org/u/zengenuity from https://www.drupal.org/project/form_options_attributes. Many thanks!
/**
 * Implements hook_theme().
 */
function wisski_pathbuilder_theme() {
  return [
    'wisski_pathbuilder__select__options_attributes' => [
      'render element' => 'elements',
      'base hook' => 'select',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function wisski_pathbuilder_theme_suggestions_select_alter(array &$suggestions, array $variables) {
  if (!empty($variables['element']['#options_attributes'])) {
    $suggestions[] = 'wisski_pathbuilder__select__options_attributes';
  }
}

/**
 * Implements hook_element_info_alter().
 */
function wisski_pathbuilder_element_info_alter(array &$info) {
  $info['checkboxes']['#process'][] = 'wisski_pathbuilder_form_process_option_attributes';
  $info['radios']['#process'][] = 'wisski_pathbuilder_form_process_option_attributes';
}

/**
 * Prepares variables for select element templates.
 */
function wisski_pathbuilder_preprocess_wisski_pathbuilder__select__options_attributes(&$variables) {
  $element = $variables['element'];
  Element::setAttributes($element, ['id', 'name', 'size']);
  RenderElement::setAttributes($element, $variables['attributes']['class']);

  $variables['attributes'] = $element['#attributes'];
  $variables['options'] = form_select_options($element);

  foreach ($element['#options'] as $key => $option) {
    if (is_array($option)) {
      // This option in an opt group.
      foreach ($option as $sub_key => $sub_option) {
        if (!empty($element['#options_attributes'][$key][$sub_key])) {
          $attributes = $element['#options_attributes'][$key][$sub_key];
          $variables['options_attributes'][$key][$sub_key] = new Attribute($attributes);
        }
      }
    }
    elseif (!empty($element['#options_attributes'][$key])) {
      // This is a normal option with attributes set.
      $attributes = $element['#options_attributes'][$key];
      $variables['options_attributes'][$key] = new Attribute($attributes);
    }
  }
}

/**
 * Processes a checkboxes or radios form element to add options_attributes.
 *
 * Adds options_wrapper_attributes and options_label_attributes
 * along with the regular attributes.
 *
 * @param array $element
 *   Radios or checkboxes Form element.
 *
 * @return array
 *   Element with the new custom attributes.
 */
function wisski_pathbuilder_form_process_option_attributes(array $element) {
  // Maps custom attribute keys to real render API attribute keys.
  $attributesTypesMap = [
    '#options_attributes'         => '#attributes',
    '#options_wrapper_attributes' => '#wrapper_attributes',
    '#options_label_attributes'   => '#label_attributes',
  ];
  foreach (Element::children($element) as $key) {
    // For each attribute type merge the custom attributes
    // with the parent's real attributes.
    foreach ($attributesTypesMap as $attributesType => $realAttributesType) {
      if (!empty($element[$attributesType][$key]) && is_array($element[$attributesType][$key])) {
        if (!empty($element[$key][$realAttributesType][$key]) && is_array($element[$key][$realAttributesType][$key])) {
          $element[$key][$realAttributesType] = array_merge($element[$key][$realAttributesType], $element[$attributesType][$key]);
        }
        else {
          $element[$key][$realAttributesType] = $element[$attributesType][$key];
        }
      }
    }
  }

  return $element;
}

