# Schema for configuration of the pathbuilder module

wisski_pathbuilder.wisski_pathbuilder.*:
  type: config_entity
  label: 'Pathbuilder'
  mapping:
    id:
      type: string
      label: 'Pathbuilder ID'
    name:
      type: label
      label: 'Label'

wisski_pathbuilder.wisski_path.*:
  type: config_entity
  label: 'Path'
  mapping:
    id:
      type: string
      label: 'Path ID'
    name:
      type: label
      label: 'Label'
  description:
      type: text
      label: 'Description'
