# Schema for configuration of the pathbuilder module

wisski_pathbuilder.wisski_pathbuilder.*:
  type: config_entity
  label: 'Pathbuilder'
  mapping:
    id:
      type: string
      label: 'Pathbuilder ID'
    name:
      type: label
      label: 'Label'
    pathtree:
      type: sequence
      'label': 'Store an array of paths as triples (ID, weight, children)'
      sequence:
        type: mapping
        mapping:
          key: 
            type: string
            label: the key
          value:
            type: string
            label: the value

wisski_pathbuilder.wisski_path.*:
  type: config_entity
  label: 'Path'
  mapping:
    id:
      type: string
      label: 'Path ID'
    name:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: string
      label: 'uuid'
    path_array:
      type: string
      label: 'Path Array'
    datatype_property:
      type: string
      label: 'Datatype Property'
    short_name:
      type: string
      label: 'Short Name'
    disamb:
      type: integer
      label: 'Disambiguation'
    length:
      type: integer
      label: 'Length'
    description:
      type: string
      label: 'Description'
    group:
      type: boolean
      label: 'Group'