<?php

use Drupal\Core\Url;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\wisski_core\WisskiBundleInterface;
use Drupal\wisski_core\WisskiEntityInterface;


// Alter the header in revisions table at wisski individuals
function wisski_doi_revision_menu_header_alter()
{
  return [new TranslatableMarkup('Revision'), new TranslatableMarkup('DOI'), new TranslatableMarkup('Operations')];
}

// Add a DOI column in revisions table at wisski individuals
function wisski_doi_revision_menu_column_alter($row, $wisski_individual, $vid)
{
  // DOI code
  $hasDOI = FALSE;
  if ($hasDOI) {
    $row[] = [
      'data' => [
        '#prefix' => '<em>',
        '#markup' => new TranslatableMarkup('Revision has DOI'),
        '#suffix' => '</em>',
      ],
    ];

  } else {
    // DOI
    $linksDOI = [];
    // maybe change later to form elements?
    $linkDOI = [
      'title' => new TranslatableMarkup('Get DOI'),
      'url' => Url::fromRoute('wisski_individual.revision_get_doi', ['wisski_individual' => $wisski_individual->id(), 'wisski_individual_revision' => $vid]),
    ];
    $linksDOI['add'] = $linkDOI;
    $row[] = [
      'data' => [
        '#type' => 'operations',
        '#links' => $linksDOI,
      ],
    ];
  }
  return $row;
}

// Add a operations menu entry "DOI Scheme" at "WissKI Groups and Bundles" in Structure
function wisski_doi_entity_operation_alter(array &$operations, \Drupal\Core\Entity\EntityInterface $entity)
{
  $entityTypeId = $entity->getEntityTypeId();
  if ($entityTypeId !== 'wisski_bundle') {
    return;
  }
  $bundleId = $entity->id();
  $editUrl = Url::fromRoute('entity.wisski_bundle.doi_scheme', ['wisski_bundle' => $bundleId]);
  $operations['doi_scheme'] = array(
    'title' => t('DOI Scheme'),
    'weight' => 100,
    'url' => $editUrl,
  );
}

function wisski_doi_menu_local_tasks_alter(&$data, $route_name, \Drupal\Core\Cache\RefinableCacheableDependencyInterface &$cacheability)
{
  if ($route_name == 'entity.wisski_bundle.edit_form') {
    $path = \Drupal::service("path.current")->getPath();
    $url = explode('/', $path);
    $bundleId = $url[4];
    dpm($data);
    $editUrl = Url::fromRoute('entity.wisski_bundle.doi_scheme', ['wisski_bundle' => $bundleId]);
    $data['tabs'][0]['entity.wisski_bundle.doi_scheme'] = [
      '#theme' => 'menu_local_task',
      '#link' => [
        'title' => t('DOI Schema'),
        'url' => $editUrl,
        'localized_options' => [
          'attributes' => [
            'title' => t('DOI Schema'),
          ],
        ],
      ],
      '#weight' => 10,
    ];

    $cacheability
      ->addCacheContexts([
        'user.permissions',
      ]);
  }
}

