<?php

use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;


function wisski_iip_image_preprocess_colorbox_formatter(&$variables) {
  $iu = $variables['image']['#uri'];

  $prerendered_paths = \Drupal::config('wisski_iip_image.settings')->get('wisski_iip_image_prerendered_path');

  $nuri = NULL;
  if(!empty($prerendered_paths)) {
    foreach($prerendered_paths as $prerendered_path) {
      $nuri = $prerendered_path . $variables['image']['#alt'];

      if(file_exists($nuri))
        break;
      $nuri = NULL;
    }
  }

  if(empty($nuri)) {
    $style = ImageStyle::load('wisski_pyramid');
    $nuri = $style->buildUri($iu);
  }

  if(strpos($nuri, "public://") !== FALSE)
    $nuri = str_replace("public://", \Drupal::service('file_system')->realpath("public://"). '/', $nuri);

  $variables['attributes']['iip'] = $nuri;
  
}

function wisski_iip_image_field_widget_form_alter(&$element, \Drupal\Core\Form\FormStateInterface $form_state, $context) {

  if(isset($element['#value_callback']) && in_array('Drupal\image\Plugin\Field\FieldWidget\ImageWidget', $element['#value_callback'])) {

    $image_factory = \Drupal::service('image.factory');
    $supported_extensions = $image_factory->getSupportedExtensions();

    $element['#upload_validators']['file_validate_extensions'][0] = implode(' ', $supported_extensions);    
  }

}