<?php

/**
 * @file
 * WissKI Mirador Views module help and theme functions.
 */

use Drupal\Core\Routing\RouteMatchInterface;

// Store WissKI Mirador preprocess theme functions in a separate .inc file.
\Drupal::moduleHandler()->loadInclude('wisski_mirador', 'inc', 'wisski_mirador.theme');

/**
 * Implements hook_help().
 */
function wisski_mirador_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wisski_mirador':
      return '<p>' . t('This is the WissKI module for the integration ' .
      'of Mirador (http://projectmirador.org/).') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function wisski_mirador_theme($existing, $type, $theme, $path) {
  return [
    'wisski_mirador' => [
      'file' => 'wisski_mirador.theme.inc',
    ],
  ];
}
