<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implementation of Hook_help.
 */
function wisski_adapter_sparql11_pb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wisski_adapter_sparql11_pb':
      return '<p>' . t('This is the adapter for communication with any ' .
        'SPARQL 1.1 endpoint. Usually you will need it!') . '</p>';
  }
}

