<?php

/**
 * @file
 * Install, update and uninstall functions for the wisski_adapter_aat module.
 */

use Drupal\Core\Database\Database;

/**
 * Delete the unused wisski_adapter_aat table from the database.
 */
function wisski_adapter_aat_update_8001(&$sandbox) {
  // This table existed for <nosebear>Mark</nosebear> reasons, but was never used
  // So we can safely drop it.
  Database::getConnection()->schema()->dropTable('wisski_adapter_aat');
}
