<?php
/*
*@author Martin Scholz, unless otherwise said
*/

use Drupal\Core\Database\Database;
use Drupal\Core\Database\IntegrityConstraintViolationException;

/**
 * Create column id and add it as primary key to wisski_merge_log table.
 */
function wisski_merge_update_8001(&$sandbox) {
  $connection = Database::getConnection();
  $schema = $connection->schema();
  try {
    $schema->addField('wisski_merge_log', 'id', [
      'description' => 'Row identifier',
      'type' => 'serial',
      'unsigned' => TRUE,
      'size' => 'big',
      'not null' => TRUE,
    ], ['primary key' => ['id']]);
  }
  catch (IntegrityConstraintViolationException $exception) {
    $text = "Cannot add column 'id' to table 'wisski_merge_log'.";
    \Drupal::messenger()->addMessage($text);
    throw new Exception($text);
  }
}


function wisski_merge_schema () {

  $schemas = array();

  $schemas['wisski_merge_log'] = array(
    'fields' => array(
      'id' => array(
        'description' => 'Row identifier',
        'type' => 'serial',
        'unsigned' => TRUE,
        'size' => 'big',
        'not null' => TRUE,
      ),
      'adapter_id' => array(
        'type' => 'varchar',
        'length' => '64',
        'not null' => TRUE,
      ),
      'variables' => array(
        'type' => 'varchar',
        'length' => '4',
        'not null' => TRUE,
      ),
      'from_uris' => array(
        'type' => 'text',
        'size' => 'normal',
        'serialize' => TRUE,
        'not null' => TRUE,
      ),
      'to_uri' => array(
        'type' => 'text',
        'size' => 'normal',
        'serialize' => FALSE,
        'not null' => TRUE,
      ),
      'affected_count' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => TRUE,
      ),
      'affected_quads' => array(
        'type' => 'text',
        'size' => 'big',
        'serialize' => TRUE,
        'not null' => FALSE,
      ),
      'timestamp' => array(
        'type' => 'int',
        'size' => 'normal',
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
  );

  return $schemas;

}
