<?php

/**
 * Implementation of hook_entity_type_alter()
 */
function wisski_merge_entity_type_alter(array &$entity_types) {
  // we add a new operation and its form for wisski individuals
  $entity_types['wisski_individual']->setFormClass('merge', 'Drupal\wisski_merge\Form\EntityMergeForm');
  // also add a link for it
  $entity_types['wisski_individual']->setLinkTemplate('merge-form', '/wisski/navigate/{wisski_individual}/merge');
}
