wisski_core.wisski_bundle.*:
  type: config_entity
  label: 'WissKI Bundle'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    field_map:
      type: mapping
      label: 'Field map'
    title_pattern:
      type: string
      label: 'Title Pattern'
    on_empty:
      type: number
      label: 'on Empty Title'
    fallback_title:
      type: string
      label: 'Entity Fallback Title'
      
views.filter.wisski_bundle:
  type: views.filter.bundle
  label: 'WBundle'
